Local auth app to radix namespace
reflex-dev/reflex-examples pull request #207
Opened 2024-02-14 13:49 UTC by ElijahAhianyo

2024-02-14 17:48 UTC, martinxu9 requested changes

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/local_auth/local_auth.py
> +        rx.chakra.color_mode_button(rx.chakra.color_mode_icon(), float="right"),
I think there's a new color mode button?

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/local_auth/login.py
> +            rx.form.root(
we can use `rx.form` instead of `rx.form.root` now

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/local_auth/login.py
> +                    rx.input.input(
should we use `rx.input` instead? there's another one below on line 95

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/local_auth/login.py
> +                        rx.form.submit(
we could get rid of the `rx.form.submit` here and use the button directly.

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/local_auth/registration.py
> +            rx.form.root(
had similar comments about `rx.form.root`, `rx.input.input` in login.py

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/requirements.txt
> +reflex>=0.3.8
should we say >=0.4.0 here?

2024-02-14 17:48 UTC, martinxu9 commented on local_auth/rxconfig.py
> +config = LocalauthConfig(
should we make it simpler? `config = rx.Config(app_name="local_auth")` instead?

2024-02-16 05:54 UTC, masenf approved these changes

2024-02-16 05:56 UTC, merged